### ISSUE TITLE
RCT info on a live VM

### ISSUE THREAD

**Issue by n-mam** [cloudbase/rct-service#1]
Hi,

I could not  check the behavior of your code (handicapped in rust and python) but just wanted to understand if you were able to get RCT CBT info, off a live VM ? The c++ code which I have attached gives back zero range count. Also, I was not able to successfully OpenVirtualDisk on the base VHDx of a checkpointed live VM... It gave me access denied. Only when I open the virtual disk with VIRTUAL_DISK_ACCESS_ALL on an offline VM that OpenVirtualDisk  is successful. Could you please advise on what could be the issue here ? 

In the attached code OpenVirtualDisk, GetVirtualDiskInformation and QueryChangesVirtualDisk are all successful on a shutdown VM. I also had changed data in the VM's vhdx after the initial checkpoint was converted to reference point but still the reported changed ranges are coming out as zero.  The web is full of ppl complaining about the native RCT API not working and unfortunately I have hit the same snag. Your implementation seems to be working fine so just thought of checking 

https://docs.microsoft.com/en-us/answers/questions/64512/rct-implementation-query.html
https://stackoverflow.com/questions/63358492/querychangesvirtualdisk-is-returning-error-invalid-handle6-even-though-openvir

[x.txt](https://github.com/cloudbase/rct-service/files/5684159/x.txt)
`cl /c /Zi /Od /EHsc x.cpp`
`link /debug x.obj`

**Comment by alexpilotti** [comment]
Yes, that took a bit to figure it out, here’s the relevant code: https://github.com/cloudbase/rct-service/blob/master/rctlib/src/lib.rs#L114

**Comment by n-mam** [comment]
Hey thanks for your response.. For the rct count being returned as 0 the issue was with the format of the rctid which I was passing to the QueryChangesVirtualDisk API. Should be as in the below sample. I was enclosing it inside the braces {} which was not correct. I used to copy if off directly the Get-VmReferencePoints PS cmdlet which had these spurious braces. The below code returns RCT changed blocks successfully.

Another observation is that it seems the ChangeTrackingState.MostRecentId which we get from GetVirtualDiskInformation for a offline vhdx is one more than what we initially created while the VM was up.. For example, while the machine was up and running, I created a checkpoint and then converted it to a reference point with rctid: rctX:4abdf273:7e45:4748:85af:78ec4af82ebf:00000000 Now when the vhdx is offline and if I query the ChangeTrackingState.MostRecentId it is giving me this : rctX:4abdf273:7e45:4748:85af:78ec4af82ebf:00000001 which fails the QueryChangesVirtualDisk with invalid rctid error. Get-VmReferencePoints cmdlet however lists only the original 000 reference point. The below function expects the user to pass the correct rctid externally.

Finally, I am still not sure about how to get this working with a live VM, because without that the whole point of doing live incremental backup goes for a toss..

[x.txt](https://github.com/cloudbase/rct-service/files/5684378/x.txt)

**Comment by n-mam** [comment]
@alexpilotti I checked the function which you pointed me at earlier and the only difference between what you had in there and what I had written was in the access mass and the OPEN_VIRTUAL_DISK_PARAMETERS structure.. You are passing access mask as 0 and version 3 as the OPEN_VIRTUAL_DISK_PARAMETERS structure version while I originally tried with VIRTUAL_DISK_ACCESS_GET_INFO (as per MSFT docs) and then when that didnt work , VIRTUAL_DISK_ACCESS_ALL to work with an offline vhdx. Doing it as per your code fixes the issue and I am able to query the RCT CBT data while the VM is up and running... This looks awesome.. many thanks.

![image](https://user-images.githubusercontent.com/17683324/102009801-eea65e00-3d5f-11eb-8dee-0143f295252f.png)

**Comment by alexpilotti** [comment]
Glad to hear that, figuring out the version took me indeed some trial and error work back then! :)
